plugins {
    id "net.neoforged.moddev" version "$moddevgradle_version"
    id "maven-publish"

    id "com.diffplug.spotless" version "8.8.0"
}

apply from: 'versioning.gradle'

version = getPublicVersion()
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = "https://api.modrinth.com/maven" }

    // YACL
    maven { url = 'https://maven.isxander.dev/releases' }

    // JEI
    maven { url = "https://maven.blamejared.com/" }

    // LambDynamicLights
    maven {
        url = "https://maven.gegy.dev"

        content {
            includeGroup "dev.lambdaurora.lambdynamiclights"
            includeGroup "dev.lambdaurora"
            includeGroup "io.github.queerbric"
        }
    }
}

neoForge {
    version = project.neoforge_version

    accessTransformers.from('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        client {
            client()
        }

        server {
            server()
        }

        data {
            clientData()

            programArguments.addAll('--mod', project.mod_id, '--all',
                    '--output', file('src/main/generated').absolutePath,
                    '--existing', file('src/main/resources').absolutePath)
        }
    }

    mods {
        "$project.mod_id" {
            sourceSet sourceSets.main
        }
    }
}

// Add the generated resources to the main source set
sourceSets {
    main {
        resources {
            srcDirs += [
                    "src/main/generated"
            ]
        }

        java {
            exclude "dev/amble/ait/compat/portal/**"
            exclude "dev/amble/ait/mixin/compat/portals/**"

            exclude "dev/amble/ait/compat/lambdynlights/**"

        }
    }
}

dependencies {
    implementation "net.objecthunter:exp4j:${project.exp4j_version}"
    jarJar(implementation("net.objecthunter:exp4j:[${project.exp4j_version},)") {
        version { prefer project.exp4j_version }
    })
    additionalRuntimeClasspath "net.objecthunter:exp4j:${project.exp4j_version}"

    implementation "com.google.code.gson:gson:${project.gson_version}"

    compileOnly "org.projectlombok:lombok:${project.lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${project.lombok_version}"

    // Compat
    implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"

    compileOnly "mezz.jei:jei-${project.minecraft_version}-neoforge-api:${project.jei_version}"
    runtimeOnly "mezz.jei:jei-${project.minecraft_version}-neoforge:${project.jei_version}"

}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE // Exclude duplicate files, I don"t why this even works
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "neoforge_version", project.neoforge_version
    inputs.property "yacl_version", project.yacl_version
    filteringCharset "UTF-8"

    exclude '.cache'

    def expansionVars = [
        "version": project.version,
        "minecraft_version": project.minecraft_version,
        "neoforge_version": project.neoforge_version,
        "yacl_version": project.yacl_version
    ]

    filesMatching("META-INF/neoforge.mods.toml") {
        expand expansionVars
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    it.options.release = 21
    it.options.compilerArgs << "-Xmaxerrs" << "100000"
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

jar {
    inputs.property "archivesName", project.base.archivesName

    // needed because inputs.properties.archivesName is not accessible configuration time
    def archivesNameValue = project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${archivesNameValue.get()}" }
    }
}

spotless {
    enforceCheck = false

    format 'misc', {
        // define the files to apply `misc` to
        target '*.gradle', '.gitattributes', '.gitignore'

        // define the steps to apply to those files
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
    }

    java {
        removeUnusedImports()
        importOrder('java', 'javax', '', 'net.minecraft', group)

        indentWithSpaces()
        trimTrailingWhitespace()

        formatAnnotations()
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            version = getArtifactVersion()
            from components.java
        }
    }

    repositories {
        maven {
            name = "ci"
            url = providers.environmentVariable("CI_MAVEN_PATH")
        }
    }
}
