# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true

# Platform
# check these on https://projects.neoforged.net/neoforged/neoforge
minecraft_version = 1.21.1
neoforge_version = 21.1.249
moddevgradle_version = 2.0.78

# Mod Properties
mod_id = ait
mod_version = 1.3.0
mod_version_qualifier = release
maven_group = dev.amblelabs
archives_base_name = ait

# Misc libraries
# MC's gson version, just for consistency
gson_version = 2.8.9
exp4j_version = 0.4.8
mixinsquared_version = 0.2.0

# MC libraries
lombok_version = 1.18.34
yacl_version = 3.8.1+1.21.1-neoforge

# Compat
jei_version = 19.51.0.417
lambdynlights_version = 4.4.0+1.21.1
